stages:
  clean:
    cmd: python3 src/clean.py data/raw/events.csv
    deps:
    - src/clean.py
    outs:
    - data/clean/events.csv
  transform:
    cmd: python3 src/transform.py data/clean/events.csv
    deps:
    - data/clean/events.csv
    - src/transform.py
    outs:
    - data/transformed/events.csv
  features:
    cmd: python3 src/features.py data/transformed/events.csv
    deps:
    - data/transformed/events.csv
    - src/features.py
    outs:
    - data/features/events.csv
